site_name: RLLR
theme: material
nav:
    - Home: index.md
    - 01.md
    - 02.md
    - 03.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - attr_list
  - admonition
