site_name: RLLR
theme:
  name: material
  logo: img/logo_head.png
  favicon: img/logo_icon.png

nav:
  - Home: index.md
  - 06.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - attr_list
  - admonition
